version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: inoveapp
      POSTGRES_USER: inove
      POSTGRES_PASSWORD: inoveSucesso2024
    ports:
      - "5432:5432"
    networks:
      - inove

  web:
    build: .
    command: >
      sh -c "chmod +x /wait-for-it.sh &&
             ./wait-for-it.sh db 5432 &&
             echo 'Postgres is up' &&
             python app/inove/create_tables.py &&
             python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - inove

  fastapi:
    build: .
    command: uvicorn app.fastapi_app:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - inove

networks:
  inove:
